# Generated by Django 6.1.1 on 2026-09-24 11:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color like #AABBCC.",
                                regex="^$|^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color like #AABBCC.",
                                regex="^$|^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                            )
                        ],
                    ),
                ),
                ("logo_url", models.URLField(blank=True, max_length=2000)),
                ("default_font", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand",
                        to="accounts.workspace",
                    ),
                ),
            ],
        ),
    ]
